AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  TableName:
    Type: String
    Default: 'myHelloTable'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

Resources:
  hello:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: nodejs10.x
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
        - SQSPollerPolicy:
            QueueName: !Ref TestQueue
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        CreateAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
        OtherOperationsAPI:
          Type: Api
          Properties:
            Path: /hello/{itemId}
            Method: ANY
DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UploadObject:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: testbucket20222
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
        - Id: DeleteContentAfter1Day
          Status: 'Enabled'
          ExpirationInDays: 1

  TestQueue:
    Type: 'AWS::SQS::Queue'